name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  source:
    runs-on: macos-latest  # השתמש ב-macos-latest במקום ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Upload code
        uses: actions/upload-artifact@v4
        with:
          name: code
          path: .
          retention-days: 1

  build:
    needs: source
    runs-on: macos-latest  # השתמש ב-macos-latest במקום ubuntu-latest
    steps:
      - name: Delete old artifacts
        uses: geekyeggo/delete-artifact@v2
        with:
          name: code
      
      - name: Download code
        uses: actions/download-artifact@v4
        with:
          name: code
          path: .

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.6'
          cache: 'pip'

      - name: Install dependencies
        run: |
          # עדכון Homebrew והתקנת libjpeg עבור Pillow
          brew update
          brew install libjpeg
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          if [ -f "./requirements.txt" ]; then
            pip install -r ./requirements.txt
          else
            echo "Error: requirements.txt not found in ./"
            exit 1
          fi

      - name: Install npm packages and run build command
        run: |
          cd ./frontend
          npm install
          npm run build
          rm -rf node_modules

      - name: Cache virtual environment
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            venv-${{ runner.os }}-

      - name: Upload code
        uses: actions/upload-artifact@v4
        with:
          name: code
          path: .
          overwrite: true
          retention-days: 1

  test:
    needs: build
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Download code
        uses: actions/download-artifact@v4
        with:
          name: code
          path: .

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.6'

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest --maxfail=1 --disable-warnings -q

  deploy:
    needs: test
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Download code
        uses: actions/download-artifact@v4
        with:
          name: code
          path: .

      - name: Deploy to production
        run: |
          echo "Deploying application..."
          # הוסף כאן את פקודות ההפצה שלך

  notify:
    needs: deploy
    runs-on: macos-latest
    steps:
      - name: Notify deployment
        run: |
          echo "Deployment successful!"
          # הוסף כאן פקודות לשליחת התראה או דוא"ל אם דרוש
